"""The SDK's type surface. GENERATED by `ow surface emit`; do not edit.

Artefact 4 of the seven (10 section 2.3), emitted from `ACTIONS` and from
`omniweave.sdk.__all__` by `omniweave.gen.sdk_stub`, and byte-diff gated by G25.
02:212 makes this file the PROOF of every `T-PUBLIC` promise the SDK makes, so a
hand edit here is a stability claim nobody reviewed.

It declares exactly what the package exports. A stub naming a symbol
`omniweave.sdk` does not bind would make it type-check and fail at runtime, which
is the defect G25 exists to catch -- so this file grows when the package does, and
never before.

The Actions this surface comes from, with the declaration behind each promise:

    name              inp                 out
    add               AddIn               AddReport
    corpora           CorporaIn           CorporaReport
    corpus.coverage   CoverageIn          Coverage
    doc.diff          DiffIn              RebindReport
    doc.grid          GridIn              Grid
    doctor            DoctorIn            DoctorReport
    explain           ExplainIn           CodeRow
    hooks.check       HooksCheckIn        HooksCheckReport
    install           InstallIn           InstallReport
    open              OpenIn              Answer
    query             QueryIn             Answer
    skills.check      SkillsCheckIn       SkillsReport
    skills.hash       SkillsHashIn        SkillsReport
    skills.install    SkillsInstallIn     SkillsReport
    skills.ls         SkillsLsIn          SkillsReport
    skills.remove     SkillsRemoveIn      SkillsReport
    skills.verify     SkillsVerifyIn      SkillsReport
    uninstall         UninstallIn         InstallReport
"""

from omniweave.sdk.reports import AddCompleted as AddCompleted
from omniweave.sdk.reports import AddPending as AddPending
from omniweave.sdk.reports import AddReport as AddReport
from omniweave.sdk.reports import CodeRow as CodeRow
from omniweave.sdk.reports import CorporaReport as CorporaReport
from omniweave.sdk.reports import CorpusCard as CorpusCard
from omniweave.sdk.reports import DoctorFinding as DoctorFinding
from omniweave.sdk.reports import DoctorReport as DoctorReport
from omniweave.sdk.reports import Gap as Gap

__all__ = [
    "AddCompleted",
    "AddPending",
    "AddReport",
    "CodeRow",
    "CorporaReport",
    "CorpusCard",
    "DoctorFinding",
    "DoctorReport",
    "Gap",
]
