"""`ow`'s argparse tree. GENERATED by `ow surface emit`; do not edit.

Artefact 3 of the seven (10 section 2.3), generated from `omniweave.surface.registry.ACTIONS` by
`omniweave.gen.cli_tree` and byte-diff gated by G25. A hand edit here is a build failure, and the
change you want belongs in `ACTIONS` or in the generator.

`build_parser()` walks `COMMANDS` and returns the parser `ow --help` renders. It parses and does
not dispatch: `set_defaults` records the `ACTIONS` name each command resolves to under
`ow_action`, which is 02:719's step 1, and steps 2-9 belong to the runtime.
"""

from __future__ import annotations

import argparse
from typing import Any, Final, NamedTuple

__all__ = [
    "ACTION_DEST",
    "COMMANDS",
    "GLOBAL_FLAGS",
    "GROUP_HELP",
    "PROG",
    "Argument",
    "Command",
    "build_parser",
]

PROG: Final[str] = "ow"
"""18:874: *"`ow` and `omniweave` are the same console script; there is no other alias."*"""

ACTION_DEST: Final[str] = "ow_action"
"""The parsed-namespace key carrying the `ACTIONS` name this command resolves to."""

GROUP_DEST: Final[str] = "ow_group"
VERB_DEST: Final[str] = "ow_verb"


class Argument(NamedTuple):
    """One positional or option, as `build_parser` hands it to argparse."""

    spelling: tuple[str, ...]
    kind: str = "str"
    nargs: str | None = None
    metavar: str | None = None
    choices: tuple[str, ...] | None = None
    default: object = None
    help: str = ""


class Command(NamedTuple):
    """One `ow` command: its words, the Actions it dispatches, and its published arguments."""

    words: tuple[str, ...]
    actions: tuple[str, ...]
    help: str
    arguments: tuple[Argument, ...]


DESCRIPTION: Final[str] = (
    "omniweave -- ask indexed documents a question and get cited passages back."
)

GLOBAL_FLAGS: Final[tuple[Argument, ...]] = (
    Argument(
        spelling=("--config",),
        metavar="PATH",
        help="the highest-precedence config source; skips the upward walk",
    ),
    Argument(
        spelling=("--corpus",),
        metavar="NAME",
        help="resolves through [corpora]; ow query is the one verb accepting a comma list",
    ),
    Argument(
        spelling=("--render",),
        choices=("text", "json", "jsonl", "rows"),
        default="text",
        help="output mode",
    ),
    Argument(
        spelling=("--quiet", "-q"),
        kind="switch",
        help="suppress the progress stream; diagnostics still print",
    ),
    Argument(
        spelling=("--verbose", "-v"),
        kind="count",
        default=0,
        help="-v adds phase timings; -vv adds the event stream at debug",
    ),
    Argument(
        spelling=("--no-color",),
        kind="switch",
        help="ANSI only when stdout is a TTY; also honours NO_COLOR",
    ),
    Argument(
        spelling=("--offline",),
        kind="switch",
        help="refuse every fetch, a toolchain install included",
    ),
    Argument(
        spelling=("--json-errors",),
        kind="switch",
        help="print an OwError as one JSON object on stderr instead of prose",
    ),
)

GROUP_HELP: Final[dict[str, str]] = {
    "doc": "diff · grid",
    "hooks": "check",
    "skills": "check · hash · install · ls · remove · verify",
}

COMMANDS: Final[tuple[Command, ...]] = (
    Command(
        words=("add",),
        actions=("add",),
        help=(
            "Index files, directories or URLs into a corpus so ow_query can cite them; "
            "billable work defers with the command that approves it"
        ),
        arguments=(
            Argument(
                spelling=("source",),
                nargs="+",
                metavar="SOURCE",
            ),
            Argument(
                spelling=("--dry-run",),
                kind="switch",
                default=False,
            ),
            Argument(
                spelling=("--schema",),
                metavar="PATH",
                help="a JSON Schema; sets unit.schema_requested",
            ),
            Argument(
                spelling=("--allow-cost",),
                kind="int",
                metavar="MICROS",
                help="approve billable work up to this many micros",
            ),
            Argument(
                spelling=("--allow-egress",),
                metavar="GRANT",
                help="the grant id that permits a fetch",
            ),
            Argument(
                spelling=("--wait",),
                kind="int",
                metavar="S",
                help="seconds to wait before reporting pending",
            ),
        ),
    ),
    Command(
        words=("corpora",),
        actions=("corpora", "corpus.coverage"),
        help=(
            "List what this server can read and what is in each corpus: counts, formats, known "
            "gaps, freshness and the capability floor"
        ),
        arguments=(
            Argument(
                spelling=("corpus",),
                nargs="?",
                metavar="CORPUS",
            ),
            Argument(
                spelling=("--detail",),
                choices=("list", "card", "coverage", "actions"),
                default="list",
            ),
            Argument(
                spelling=("--summarize",),
                kind="switch",
                help="write the corpus abstract, recording a producer",
            ),
            Argument(
                spelling=("--scope",),
                metavar="SCOPE",
            ),
        ),
    ),
    Command(
        words=("doc", "diff"),
        actions=("doc.diff",),
        help=(
            "Compare two generations of one document: what carried, what was revised, what is "
            "new, and whether the newer generation was quarantined rather than committed"
        ),
        arguments=(
            Argument(
                spelling=("ref",),
                metavar="REF",
            ),
            Argument(
                spelling=("--from-gen",),
                kind="int",
                metavar="FROM_GEN",
            ),
            Argument(
                spelling=("--to-gen",),
                kind="int",
                metavar="TO_GEN",
            ),
        ),
    ),
    Command(
        words=("doc", "grid"),
        actions=("doc.grid",),
        help=(
            "Read one table as an exactly-once grid: every cell at its slot, the header row "
            "and column, and the merges that would otherwise be counted twice"
        ),
        arguments=(
            Argument(
                spelling=("ref",),
                metavar="REF",
            ),
        ),
    ),
    Command(
        words=("doctor",),
        actions=("doctor",),
        help=(
            "Check this deployment: every resolved configuration value with its source, the "
            "driver and toolchain probes, and a fix command for every warning"
        ),
        arguments=(
            Argument(
                spelling=("--runtime",),
                kind="switch",
                default=False,
            ),
        ),
    ),
    Command(
        words=("explain",),
        actions=("explain",),
        help=(
            "Resolve an OW-* code or symbol to what it means and the exact command that clears "
            "it; reads no corpus, so it answers on a machine with no store at all"
        ),
        arguments=(
            Argument(
                spelling=("code",),
                metavar="CODE",
            ),
        ),
    ),
    Command(
        words=("hooks", "check"),
        actions=("hooks.check",),
        help=(
            "Run each installed hook command as its host would, with a probe payload in a "
            "scratch project, and say which failed and why"
        ),
        arguments=(),
    ),
    Command(
        words=("install",),
        actions=("install",),
        help=(
            "Wire agent hosts to omniweave: the MCP entry, one permission wildcard, the "
            "instruction block, hooks and the core skill, each recorded in a receipt"
        ),
        arguments=(
            Argument(
                spelling=("--target",),
                metavar="TARGET",
                default="auto",
            ),
            Argument(
                spelling=("--location",),
                metavar="LOCATION",
            ),
            Argument(
                spelling=("--hooks",),
                metavar="HOOKS",
            ),
            Argument(
                spelling=("--skills",),
                metavar="SKILLS",
            ),
            Argument(
                spelling=("--allow-cli",),
                kind="switch",
                default=False,
            ),
            Argument(
                spelling=("--check",),
                kind="switch",
                default=False,
            ),
            Argument(
                spelling=("--print-config",),
                metavar="PRINT_CONFIG",
            ),
            Argument(
                spelling=("--dry-run",),
                kind="switch",
                default=False,
            ),
            Argument(
                spelling=("--yes",),
                kind="switch",
                default=False,
            ),
        ),
    ),
    Command(
        words=("open",),
        actions=("open",),
        help=(
            "Fetch the exact passages behind an address you already hold: a cite, a page "
            "range, or a whole document"
        ),
        arguments=(
            Argument(
                spelling=("ref",),
                nargs="+",
                metavar="REF",
                help=(
                    "'d7#412' | 'handbook:d7#412' | 'policy.pdf#p14/3' | 'policy.pdf#p12-18' | "
                    "'policy.pdf'"
                ),
            ),
            Argument(
                spelling=("--context",),
                kind="int",
                metavar="CONTEXT",
                default=1,
            ),
            Argument(
                spelling=("--layers",),
                kind="csv",
                metavar="LAYERS",
            ),
            Argument(
                spelling=("--max-chars",),
                kind="int",
                metavar="MAX_CHARS",
            ),
            Argument(
                spelling=("--raw",),
                kind="switch",
                help="the retained bytes, without the packer's rendering",
            ),
            Argument(
                spelling=("--want-impact",),
                kind="switch",
                help="ow:impact for a batch; a single-block ref gets it anyway",
            ),
        ),
    ),
    Command(
        words=("query",),
        actions=("query",),
        help=(
            "Ask an indexed corpus a question and get cited passages, a verdict, and the gaps "
            "that could be hiding an answer"
        ),
        arguments=(
            Argument(
                spelling=("query",),
                metavar="QUERY",
            ),
            Argument(
                spelling=("--scope",),
                metavar="SCOPE",
                help="'policy.pdf' | 'policy.pdf#p12-40' | 'd7' | 'contracts/2025/**'",
            ),
            Argument(
                spelling=("--want",),
                choices=("passages", "table", "fields", "outline", "related"),
                default="passages",
            ),
            Argument(
                spelling=("--max-rung",),
                choices=("gate", "decode", "repair", "page", "regen", "degrade", "enrich"),
            ),
            Argument(
                spelling=("--max-chars",),
                kind="int",
                metavar="MAX_CHARS",
            ),
            Argument(
                spelling=("--k",),
                kind="int",
                metavar="N",
                help="candidates per channel before fusion",
            ),
            Argument(
                spelling=("--mode",),
                choices=("find", "cite", "explore", "prove_absent"),
                help="the planner's mode; never set by --want",
            ),
            Argument(
                spelling=("--fail-on",),
                metavar="STATE[,STATE]",
                help="exit 3 on absent, 4 on degraded, instead of 0",
            ),
            Argument(
                spelling=("--explain",),
                kind="switch",
                help="print the routing decision with the answer",
            ),
        ),
    ),
    Command(
        words=("skills", "check"),
        actions=("skills.check",),
        help=(
            "Say whether the installed skills are this release's: a stale or missing core "
            "skill fails, an outdated or orphaned on-demand one is reported"
        ),
        arguments=(
            Argument(
                spelling=("--check",),
                kind="switch",
                default=False,
            ),
        ),
    ),
    Command(
        words=("skills", "hash"),
        actions=("skills.hash",),
        help=(
            "Print the sha256-bundle-1 digest, file count and byte count of every skill bundle "
            "this release ships, for a release PR to pin"
        ),
        arguments=(),
    ),
    Command(
        words=("skills", "install"),
        actions=("skills.install",),
        help=(
            "Copy a shipped skill bundle into every discovered agent-host skills directory, "
            "verified on its whole-bundle digest and recorded in skills-lock.json"
        ),
        arguments=(
            Argument(
                spelling=("name",),
                nargs="+",
                metavar="NAME",
            ),
        ),
    ),
    Command(
        words=("skills", "ls"),
        actions=("skills.ls",),
        help=(
            "List the skills this release ships, with tier and digest, and which agent-host "
            "skills directories hold each one and on whose record"
        ),
        arguments=(),
    ),
    Command(
        words=("skills", "remove"),
        actions=("skills.remove",),
        help=(
            "Take a skill out of every directory skills-lock.json says ow skills install put "
            "it in, on its digest; a modified or foreign copy is kept"
        ),
        arguments=(
            Argument(
                spelling=("name",),
                nargs="+",
                metavar="NAME",
            ),
            Argument(
                spelling=("--yes",),
                kind="switch",
                default=False,
            ),
        ),
    ),
    Command(
        words=("skills", "verify"),
        actions=("skills.verify",),
        help=(
            "Re-hash every skill bundle skills-lock.json says was installed and name each "
            "mismatch: expected digest, observed digest, first differing path"
        ),
        arguments=(
            Argument(
                spelling=("--all",),
                kind="switch",
                default=False,
            ),
        ),
    ),
    Command(
        words=("uninstall",),
        actions=("uninstall",),
        help=(
            "Take omniweave out of agent hosts exactly: every path the install receipt names, "
            "on its digest, and never the corpus index"
        ),
        arguments=(
            Argument(
                spelling=("--target",),
                metavar="TARGET",
                default="all",
            ),
            Argument(
                spelling=("--location",),
                metavar="LOCATION",
            ),
            Argument(
                spelling=("--keep-cli",),
                kind="switch",
                default=False,
            ),
            Argument(
                spelling=("--yes",),
                kind="switch",
                default=False,
            ),
        ),
    ),
)


def _add(parser: argparse.ArgumentParser, argument: Argument, *, suppress: bool = False) -> None:
    """Add one `Argument` to one parser, translating `kind` into argparse's vocabulary."""
    options: dict[str, Any] = {}
    if argument.kind == "switch":
        options["action"] = "store_true"
    elif argument.kind == "count":
        options["action"] = "count"
    else:
        if argument.kind == "int":
            options["type"] = int
        if argument.nargs is not None:
            options["nargs"] = argument.nargs
        if argument.metavar is not None:
            options["metavar"] = argument.metavar
        if argument.choices is not None:
            options["choices"] = list(argument.choices)
    if suppress:
        options["default"] = argparse.SUPPRESS
    elif argument.default is not None:
        options["default"] = argument.default
    if argument.help:
        options["help"] = argument.help
    parser.add_argument(*argument.spelling, **options)


def _common(*, defaults: bool) -> argparse.ArgumentParser:
    """The global flags as a parent parser. Built twice, and the second time with no defaults.

    18:887 says the eight are *"accepted before or after the verb, on every command"*, and argparse
    makes the second half a trap rather than a setting: a subparser applies its OWN defaults after
    the root has parsed, so `ow --render json query "..."` is silently overwritten by the
    subparser's `text` unless the subparser declines to have a default at all. `argparse.SUPPRESS`
    is that declining -- the attribute is set only when the flag is actually written -- and the
    root's copy carries the real defaults.
    """
    common = argparse.ArgumentParser(add_help=False)
    for flag in GLOBAL_FLAGS:
        _add(common, flag, suppress=not defaults)
    return common


def build_parser() -> argparse.ArgumentParser:
    """The parser `ow --help` renders. Pure: it reads `COMMANDS` and touches nothing else."""
    root = argparse.ArgumentParser(
        prog=PROG, parents=[_common(defaults=True)], description=DESCRIPTION
    )
    inherited = _common(defaults=False)
    nodes: dict[tuple[str, ...], argparse.ArgumentParser] = {(): root}
    holders: dict[tuple[str, ...], Any] = {}
    for command in COMMANDS:
        for depth in range(1, len(command.words)):
            branch = command.words[:depth]
            if branch not in nodes:
                _open(nodes, holders, branch, GROUP_HELP.get(branch[-1], ""), inherited)
        node = _open(nodes, holders, command.words, command.help, inherited)
        for argument in command.arguments:
            _add(node, argument)
        node.set_defaults(**{ACTION_DEST: command.actions[0]})
    return root


def _open(
    nodes: dict[tuple[str, ...], argparse.ArgumentParser],
    holders: dict[tuple[str, ...], Any],
    words: tuple[str, ...],
    help_text: str,
    inherited: argparse.ArgumentParser,
) -> argparse.ArgumentParser:
    """The parser for `words`, creating its parent's subparser group on first use."""
    parent_words = words[:-1]
    holder = holders.get(parent_words)
    if holder is None:
        holder = nodes[parent_words].add_subparsers(
            dest=VERB_DEST if parent_words else GROUP_DEST,
            metavar="<verb>" if parent_words else "<group>",
        )
        holders[parent_words] = holder
    node = holder.add_parser(
        words[-1],
        parents=[inherited],
        help=help_text,
        description=help_text,
    )
    nodes[words] = node
    return node
