"""D645 end to end: an edited file is read again, and the version it replaced leaves search.

One PDF through a real `ow add`, `ow query` and `ow open`, generated by the reference-corpus
generator so its text is known:

- indexed, it answers its launch code, `AARDVARK`, under the cite `d1#1`;
- edited to say `ZEBRAFISH`, and `ow add docs` again: the report says one file changed and one
  earlier version left search. The new text is found, and the old one is `absent`, where before
  D645 the old text answered and the new one was a confident `absent`;
- the old cite still resolves, to a statement that it was retired, as 03:1159 requires;
- a file that did not change is not read again, even one indexed too soon after it was written for
  its `mtime` to prove it: its bytes are hashed instead.
"""

from __future__ import annotations

import importlib.util
import json
import os
import sqlite3  # noqa: TID251 -- the assertions read the store the run wrote.
import sys
from pathlib import Path
from types import ModuleType

import pytest
from omniweave_core.host.subproc import Captured, run_captured

pytestmark = pytest.mark.conform

REPO = Path(__file__).resolve().parents[4]
PROJECT = (
    '[corpora.docs]\npath = ".omniweave/docs.owstore"\n'
    '[serve]\ndefault_corpus = "docs"\n'
    "[drivers]\nallow_unattested = true\nrequire_lock = false\ninproc = []\n"
)
TIMEOUT_S = 300


def _generator() -> ModuleType:
    path = REPO / "fixtures" / "gen" / "gen_reference_corpora.py"
    spec = importlib.util.spec_from_file_location("_t3_gen_reference_corpora", path)
    assert spec is not None and spec.loader is not None, path
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _run(project: Path, env: dict[str, str], *argv: str) -> Captured:
    return run_captured(
        (sys.executable, "-m", "omniweave", *argv),
        stdin=b"",
        cwd=str(project),
        env=env,
        timeout_s=TIMEOUT_S,
    )


def _ow(project: Path, env: dict[str, str], *argv: str) -> str:
    done = _run(project, env, *argv)
    shown = (done.stdout + done.stderr).decode("utf-8", "replace")
    assert done.returncode == 0, shown[-3000:]
    return shown


def _answer(project: Path, env: dict[str, str], question: str) -> dict[str, object]:
    done = _run(project, env, "query", question, "--render", "json")
    assert done.returncode == 0, done.stderr.decode("utf-8", "replace")[-3000:]
    return json.loads(done.stdout)


def _texts(answer: dict[str, object]) -> list[str]:
    return [str(hit.get("text", "")) for hit in answer["evidence"]]  # type: ignore[union-attr]


def test_an_edited_file_is_read_again_and_its_old_version_leaves_search(tmp_path: Path) -> None:
    gen = _generator()
    project = tmp_path / "project"
    (project / "docs").mkdir(parents=True)
    (project / "omniweave.toml").write_text(PROJECT, encoding="utf-8")
    note = project / "docs" / "note.pdf"
    note.write_bytes(gen.pdf_bytes([["The launch code is AARDVARK."]], title="Note"))
    other = project / "docs" / "other.pdf"
    other.write_bytes(gen.pdf_bytes([["An unrelated memo about parking."]], title="Memo"))
    home = tmp_path / "home"
    home.mkdir()
    keep = {k: v for k, v in os.environ.items() if k not in {"PYTHONUTF8", "PYTHONIOENCODING"}}
    env = {
        **keep,
        "HOME": str(home),
        "USERPROFILE": str(home),
        "OMNIWEAVE_HOME": str(tmp_path / "ow"),
    }

    #  1. Indexed: the old text answers, under a cite.
    _ow(project, env, "add", "docs")
    first = _answer(project, env, "AARDVARK")
    assert _texts(first) == ["The launch code is AARDVARK."]
    old_cite = str(first["evidence"][0]["cite"])  # type: ignore[index]

    #  2. Edited, and added again at once. `other.pdf` was indexed within 2 s of being written, so
    #     `stat_fresh` cannot prove it fresh: it is hashed, found unchanged, and not read again.
    note.write_bytes(gen.pdf_bytes([["The launch code is ZEBRAFISH now."]], title="Note"))
    added = _ow(project, env, "add", "docs")
    assert "; 1 indexed file(s) read again: changed" in added, added
    assert "retire    1 earlier versions of changed files leave search" in added
    assert _texts(_answer(project, env, "ZEBRAFISH")) == ["The launch code is ZEBRAFISH now."]
    gone = _answer(project, env, "AARDVARK")
    assert (gone["state"], _texts(gone)) == ("absent", [])

    #  3. The old cite resolves, to a statement that it was retired.
    opened = _run(project, env, "open", old_cite)
    shown = (opened.stdout + opened.stderr).decode("utf-8", "replace")
    assert f"{old_cite} was retired" in shown
    assert "source_deleted" in shown

    #  4. Nothing changed since, the edit included: nothing is read again, nothing retired.
    again = _ow(project, env, "ingest", "docs")
    assert "read again" not in again
    assert "retire " not in again
    connection = sqlite3.connect(project / ".omniweave" / "docs.owstore")
    try:
        units = connection.execute("SELECT state, stale_since FROM unit").fetchall()
        history = connection.execute(
            "SELECT DISTINCT doc_ord, reason, superseded_by FROM block_history"
        ).fetchall()
        live = connection.execute(
            "SELECT count(*) FROM block WHERE doc_ord = ? AND state = 0", (history[0][0],)
        ).fetchone()
    finally:
        connection.close()
    assert units == [("settled", None), ("settled", None)]
    assert [(reason, successor) for _doc, reason, successor in history] == [
        ("source_deleted", None)
    ]
    assert live == (0,)
