"""`ow eval run --suite absence --deterministic-half`: every built Injector over its fixtures.

Q-G7's paired-damage half (13-quality.md section 8.6), and the line of P6's exit criteria it stands
for (16-roadmap.md, section 9):

    uv run ow eval run --suite absence --deterministic-half

**Why a `tools/` script.** `ow eval` is P10's verb group and does not exist, so this is the
standing pattern (ledger D25): the library half is `omniweave_conform.damage` -- the thirteen-row
table, the Injectors built, and `assess()` -- and this file builds fixtures, runs `ow`, reads the
verdicts and prints. It is the one place allowed to import `omniweave`, which the harness needs for
13:1306's *"parses the string against the `ow` Action registry"*.

## One `(Injector, fixture)` pair, four runs

1. **pristine**: the fixture's documents, generated by `fixtures/gen/gen_reference_corpora.py`,
   through a real `ow add`. Shared by every pair over the same documents.
2. **damaged**: the same documents with the Injector applied to one file, built from scratch,
   under `PROJECT` and the Injector's own `config` (`inflate`'s `[ingest] max_parts`, D644).
3. **the fix**: the damaged run's `DegradeCause.fix` for the expected gate, split by
   `damage.split_fix()`, admitted against the registry by `admit()`, and run with no shell. A
   source-bytes Injector restores the file first (D640). `encrypt` restores nothing: its
   `Injector.repair` does what the cause's detail tells a user to, a `password_file` line and an
   `OW_SECRET_*` variable in the fix child's environment (D643). `inflate` restores nothing
   either: its repair raises `[ingest] max_parts` through the twin the detail names (D644).
4. **fixed**: the verdict after the fix, which must be the pristine run's.

Each project has its own `HOME` and `OMNIWEAVE_HOME`, as `bench/serve/first_answer.py` lays them
out, so nothing of the user's is read or written. `ow add` and the fix are children; a query is
one read-only `execute()` in this process, which is what `ow query` runs (`surface/query.py`), so
the assertions read the `Verdict` itself and never the rendered prose.

**The fix runs as a child, not in this process. D640.** 13:1306 says *"in-process with no
shell"*, and the property that sentence protects is the second half: the argv is the parsed one
and nothing interprets it. A child is how the fix gets the fixture's own `HOME`, `OMNIWEAVE_HOME`
and working directory, which an in-process call would have to patch into this process's
`os.environ` and `os.chdir`, and a patch that leaked would make the next pair's run read the
previous pair's store.

## Exit codes

`0` every pair passed. `1` a pair failed. `2` the suite could not run: no register row, a fixture
that would not build, or an unknown `--injector`.
"""

from __future__ import annotations

import argparse
import contextlib
import importlib.util
import io
import json
import os
import shutil
import sys
import tempfile
import time
import tomllib
from collections.abc import Callable, Mapping, Sequence
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any, Final

REPO: Final = Path(__file__).resolve().parent.parent
REGISTER: Final = REPO / "eval" / "gates.toml"
GENERATOR: Final = REPO / "fixtures" / "gen" / "gen_reference_corpora.py"

for _dist in sorted((REPO / "packages").iterdir()) if (REPO / "packages").is_dir() else []:
    _src = _dist / "src"
    if _src.is_dir() and str(_src) not in sys.path:
        sys.path.insert(0, str(_src))

from omniweave_conform.damage import (  # noqa: E402
    INJECTORS,
    TABLE,
    Assessment,
    FixRefusedError,
    Injector,
    Observed,
    assess,
    observed,
    split_fix,
)
from omniweave_core.host.subproc import Captured, run_captured  # noqa: E402

__all__ = ["FIXTURES", "METRIC", "Fixture", "admit", "main"]

METRIC: Final = "degradation_detection"
EXIT_OK, EXIT_FAIL, EXIT_USAGE = 0, 1, 2
ADD_TIMEOUT_S: Final = 600

PROJECT: Final = (
    '[corpora.docs]\npath = ".omniweave/docs.owstore"\n'
    '[serve]\ndefault_corpus = "docs"\n'
    "[drivers]\nallow_unattested = true\nrequire_lock = false\ninproc = []\n"
)
"""`bench/serve/first_answer.py`'s project: one corpus, the default, and D576's three opt-ins."""


@dataclass(frozen=True, slots=True)
class Fixture:
    """Documents from one reference corpus, the file to damage, and the question to ask."""

    corpus: str
    paths: tuple[str, ...]
    target: str
    question: str

    @property
    def name(self) -> str:
        return f"{self.corpus}/{self.target}"


_ARCHIVE: Final = (
    "insurance/home-policy-2024.pdf",
    "letters/oakridge-renewal-2024.docx",
    "medical/lab-results-2024.pdf",
    "tax/tax-summary-2023.docx",
)

_ROOM: Final = (
    "finance/cap-table-2024.xlsx",
    "hr/headcount-2024.xlsx",
    "legal/nda-northwind.docx",
)

FIXTURES: Final[Mapping[str, tuple[Fixture, ...]]] = {
    "encrypt": (
        Fixture(
            "personal_archive",
            _ARCHIVE,
            "medical/lab-results-2024.pdf",
            "What was the LDL cholesterol result in the 2024 lab results?",
        ),
        Fixture(
            "personal_archive",
            _ARCHIVE,
            "insurance/home-policy-2024.pdf",
            "What does section 5 of the home insurance policy say about flood damage?",
        ),
    ),
    "chaos": (
        Fixture(
            "data_room",
            _ROOM,
            "hr/headcount-2024.xlsx",
            "What total headcount does the 2024 headcount report give?",
        ),
        Fixture(
            "personal_archive",
            _ARCHIVE,
            "medical/lab-results-2024.pdf",
            "What was the LDL cholesterol result in the 2024 lab results?",
        ),
    ),
    "inflate": (
        Fixture(
            "personal_archive",
            _ARCHIVE,
            "medical/lab-results-2024.pdf",
            "What was the LDL cholesterol result in the 2024 lab results?",
        ),
        Fixture(
            "personal_archive",
            _ARCHIVE,
            "insurance/home-policy-2024.pdf",
            "What does section 5 of the home insurance policy say about flood damage?",
        ),
    ),
    "mask_format": (
        Fixture(
            "personal_archive",
            _ARCHIVE,
            "tax/tax-summary-2023.docx",
            "What refund does the 2023 tax summary show?",
        ),
        Fixture(
            "personal_archive",
            _ARCHIVE,
            "medical/lab-results-2024.pdf",
            "What was the LDL cholesterol result in the 2024 lab results?",
        ),
    ),
}
"""Each built Injector's fixtures: an OOXML file and a PDF, the two structures detection reads.
`encrypt` applies to a PDF alone (ADR-15 D15.6), so both of its fixtures are PDFs, one page and
three. So do `inflate`'s, padded to one page above `INFLATE_MAX_PARTS`: by three pages and by one.
Masked, they are the two ways it names a format (`route/detect.py` steps 2 and 3); cut, they are
the two structural checks of `unit.corrupt`, a ZIP central directory and a PDF trailer (D641).
`chaos` takes its OOXML file from the data room, a spreadsheet, as the bench's own task does."""


def emit(line: str = "") -> None:
    sys.stdout.write(line + "\n")
    sys.stdout.flush()


# ---------------------------------------------------------------------------------------------
# Building and reading a fixture
# ---------------------------------------------------------------------------------------------


def _generator() -> ModuleType:
    spec = importlib.util.spec_from_file_location("omniweave_gen_reference_corpora", GENERATOR)
    if spec is None or spec.loader is None:  # pragma: no cover -- the file is in this repo
        msg = f"cannot load {GENERATOR}"
        raise RuntimeError(msg)
    module = sys.modules.get(spec.name)
    if module is None:
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
    return module


def _documents(fixture: Fixture) -> dict[str, bytes]:
    wanted = set(fixture.paths)
    found = {
        doc.path: doc.to_bytes()
        for doc in _generator().documents(fixture.corpus, "quick")
        if doc.path in wanted
    }
    missing = wanted - set(found)
    if missing:
        msg = f"{fixture.corpus} has no {sorted(missing)} at quick scale"
        raise RuntimeError(msg)
    return found


def _env(work: Path) -> dict[str, str]:
    kept = {k: v for k, v in os.environ.items() if k not in {"PYTHONUTF8", "PYTHONIOENCODING"}}
    home = work / "home"
    home.mkdir(parents=True, exist_ok=True)
    return {**kept, "HOME": str(home), "USERPROFILE": str(home), "OMNIWEAVE_HOME": str(work / "ow")}


def _ow(work: Path, argv: Sequence[str], extra: Mapping[str, str] | None = None) -> Captured:
    """`ow <argv>` in `work/project`, as a child with no shell. Never raises (`run_captured`).

    `extra` is added to the fixture's environment: an `Injector.repair`'s secret, for the fix."""
    return run_captured(
        (sys.executable, "-m", "omniweave", *argv),
        stdin=b"",
        cwd=str(work / "project"),
        env={**_env(work), **(extra or {})},
        timeout_s=ADD_TIMEOUT_S,
    )


def build(work: Path, documents: Mapping[str, bytes], *, config: str = "") -> None:
    """Write the project and its documents under `work`, then `ow add docs`.

    `config` ends the project's `omniweave.toml`: an `Injector.config`, for a damaged build."""
    project = work / "project"
    (project / "docs").mkdir(parents=True)
    (project / "omniweave.toml").write_text(PROJECT + config, encoding="utf-8")
    for path, data in documents.items():
        target = project / "docs" / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    added = _ow(work, ("add", "docs"))
    if added.returncode != 0:
        tail = added.stderr.decode("utf-8", "replace")[-1200:]
        msg = f"ow add over {work} exited {added.returncode}:\n{tail}"
        raise RuntimeError(msg)


def ask(work: Path, question: str) -> Observed:
    """One read-only `execute()` over the fixture's store: `ow query`'s own read."""
    from omniweave_core.retrieve.execute import execute  # noqa: PLC0415
    from omniweave_core.retrieve.types import Query, RetrievalPolicy  # noqa: PLC0415
    from omniweave_core.store import reader as store_reader  # noqa: PLC0415
    from omniweave_core.store import sqlite as store_sqlite  # noqa: PLC0415

    connection = store_sqlite.connect_readonly(work / "project" / ".omniweave" / "docs.owstore")
    try:
        reader = store_reader.SqliteReader(connection, now_ns=time.time_ns())
        retrieval = execute(reader, Query(text=question), RetrievalPolicy())
    finally:
        connection.close()
    return observed(retrieval.response.verdict)


# ---------------------------------------------------------------------------------------------
# 13:1306: the fix, parsed against the registry
# ---------------------------------------------------------------------------------------------


def admit(argv: Sequence[str]) -> str | None:
    """`None` if `ow <argv>` names a runnable Action with that Action's parameters, else why not.

    Three checks, each one 13:1306 names:
    - the words resolve through `surface.registry.resolve_cli` to a verb, an argument or a bare
      root, and never to `no-such-root`, `no-such-verb`, `absent` or `unrostered`;
    - the root is one this build dispatches (`omniweave.__main__.DISPATCHED`), so it runs;
    - the whole argv parses under the generated CLI tree, so every flag is that Action's.
    """
    from omniweave.__main__ import DISPATCHED  # noqa: PLC0415
    from omniweave.cli import build_parser  # noqa: PLC0415
    from omniweave.surface.registry import resolve_cli  # noqa: PLC0415

    words = [word for word in argv[1:] if not word.startswith("-")]
    status = resolve_cli(words[:2])
    if status not in {"verb", "argument", "bare"}:
        return f"`{' '.join(words[:2])}` resolves as {status}, not as an Action"
    if words[0] not in DISPATCHED:
        return f"`ow {words[0]}` is an Action this build does not run"
    sink = io.StringIO()
    try:
        with contextlib.redirect_stderr(sink):
            build_parser().parse_args(list(argv[1:]))
    except SystemExit:
        return f"the parameters are not the Action's: {sink.getvalue().strip()}"
    return None


# ---------------------------------------------------------------------------------------------
# One pair
# ---------------------------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Damaged:
    """One pair's damaged run, and the run after its fix, or why the fix did not run."""

    damaged: Observed
    fixed: Observed | None
    refusal: str | None


def run_pair(
    injector: Injector,
    fixture: Fixture,
    work: Path,
    *,
    documents: Mapping[str, bytes],
    admit_fix: Callable[[Sequence[str]], str | None] = admit,
) -> Damaged:
    """Damage one file, build, read, run the fix, and read again. Needs no pristine run."""
    damaged_docs = dict(documents)
    damaged_docs[fixture.target] = injector.transform(documents[fixture.target])
    build(work, damaged_docs, config=injector.config)
    damaged = ask(work, fixture.question)
    cause = damaged.cause(injector.row.gate)
    refusal: str | None
    argv: tuple[str, ...] = ()
    try:
        argv = split_fix("" if cause is None else cause.fix)
        refusal = admit_fix(argv)
    except FixRefusedError as exc:
        refusal = str(exc)
    if refusal is not None:
        return Damaged(damaged, None, refusal)
    if injector.restores_source:
        (work / "project" / "docs" / fixture.target).write_bytes(documents[fixture.target])
    extra: Mapping[str, str] = {}
    if injector.repair is not None:
        try:
            repair = injector.repair("" if cause is None else cause.detail)
        except FixRefusedError as exc:
            return Damaged(damaged, None, str(exc))
        for relative, text in repair.append.items():
            with (work / "project" / relative).open("a", encoding="utf-8") as handle:
                handle.write(text)
        extra = repair.env
    ran = _ow(work, argv[1:], extra)
    if ran.returncode != 0:
        tail = ran.stderr.decode("utf-8", "replace")[-600:]
        return Damaged(damaged, None, f"the fix exited {ran.returncode} {ran.failed}: {tail}")
    return Damaged(damaged, ask(work, fixture.question), None)


def _pristine(
    work: Path, documents: Mapping[str, bytes], questions: Sequence[str]
) -> list[Observed]:
    build(work, documents)
    return [ask(work, question) for question in questions]


# ---------------------------------------------------------------------------------------------
# The run
# ---------------------------------------------------------------------------------------------


def _row(register: Path) -> Mapping[str, Any] | None:
    if not register.is_file():
        return None
    rows = tomllib.loads(register.read_text(encoding="utf-8")).get("gate", [])
    return next((row for row in rows if row.get("metric") == METRIC), None)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ow_damage",
        description="The deterministic half of the absence suite: every built Injector, "
        "damaged, read, fixed and read again (13-quality.md section 8.6).",
    )
    parser.add_argument("--deterministic-half", action="store_true", help="the only half built")
    parser.add_argument("--injector", action="append", help="run only these Injectors")
    parser.add_argument("--keep", type=Path, help="keep every fixture project under this folder")
    parser.add_argument("--json", type=Path, help="also write the report as JSON here")
    parser.add_argument(
        "--workers",
        type=int,
        default=min(4, os.cpu_count() or 1),
        help="fixture builds run at once; each is one `ow add` (default: min(4, cores))",
    )
    parser.add_argument("--register", type=Path, default=REGISTER)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run every built Injector over its fixtures. 0 passed, 1 failed, 2 could not run."""
    args = _parser().parse_args(argv)
    row = _row(args.register)
    if row is None:
        emit(f"ow_damage: {args.register} has no {METRIC} row; the gate has no budget to meet")
        return EXIT_USAGE
    chosen = list(INJECTORS) if not args.injector else list(dict.fromkeys(args.injector))
    unknown = [name for name in chosen if name not in INJECTORS]
    if unknown:
        owed = [one.name for one in TABLE if one.name not in INJECTORS]
        emit(f"ow_damage: {unknown} are not built; built: {list(INJECTORS)}; owed: {owed}")
        return EXIT_USAGE

    root = args.keep or Path(tempfile.mkdtemp(prefix="ow-damage-"))
    emit(
        f"{METRIC}  (hard at {float(row['budget']):.4f} over every (Injector, fixture) pair; "
        f"owner {row.get('owner')}, review by {row.get('review_by')})"
    )
    emit()
    pairs = [
        (INJECTORS[name], index, fixture)
        for name in chosen
        for index, fixture in enumerate(FIXTURES.get(name, ()))
    ]
    results: list[Assessment] = []
    try:
        sets = list(dict.fromkeys((fixture.corpus, fixture.paths) for _i, _n, fixture in pairs))
        documents = {
            key: _documents(next(f for _i, _n, f in pairs if (f.corpus, f.paths) == key))
            for key in sets
        }
        with ThreadPoolExecutor(max_workers=max(1, args.workers)) as pool:
            pristine_runs = {
                key: pool.submit(
                    _pristine,
                    root / f"pristine-{number}",
                    documents[key],
                    [f.question for _i, _n, f in pairs if (f.corpus, f.paths) == key],
                )
                for number, key in enumerate(sets)
            }
            damaged_runs = [
                pool.submit(
                    run_pair,
                    injector,
                    fixture,
                    root / f"{injector.name}-{index}",
                    documents=documents[(fixture.corpus, fixture.paths)],
                )
                for injector, index, fixture in pairs
            ]
            pristine_of = {key: future.result() for key, future in pristine_runs.items()}
            for (injector, _index, fixture), future in zip(pairs, damaged_runs, strict=True):
                key = (fixture.corpus, fixture.paths)
                same_set = [f for _i, _n, f in pairs if (f.corpus, f.paths) == key]
                pristine = pristine_of[key][same_set.index(fixture)]
                run = future.result()
                result = assess(
                    injector,
                    fixture.name,
                    pristine=pristine,
                    damaged=run.damaged,
                    fixed=run.fixed,
                    fix_refusal=run.refusal,
                )
                results.append(result)
                emit(f"  {'ok  ' if result.ok else 'FAIL'}  {injector.name} x {fixture.name}")
                for clause in result.clauses:
                    mark = "ok  " if clause.ok else "FAIL"
                    emit(f"          {mark}  {clause.name}: {clause.why}")
                emit()
    except (RuntimeError, OSError) as exc:
        emit(f"ow_damage: the suite could not run: {type(exc).__name__}: {exc}")
        return EXIT_USAGE
    finally:
        if args.keep is None:
            shutil.rmtree(root, ignore_errors=True)

    passed = sum(1 for result in results if result.ok)
    owed = [one.name for one in TABLE if one.name not in INJECTORS]
    value = passed / len(results) if results else None
    emit(f"  population: {len(INJECTORS)} of {len(TABLE)} Injectors built; owed: {', '.join(owed)}")
    if args.json is not None:
        report = {
            "metric": METRIC,
            "value": value,
            "pairs": [
                {
                    "injector": result.injector,
                    "fixture": result.fixture,
                    "ok": result.ok,
                    "clauses": [{"name": c.name, "ok": c.ok, "why": c.why} for c in result.clauses],
                }
                for result in results
            ],
            "built": list(INJECTORS),
            "owed": owed,
        }
        args.json.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    if value is None:
        emit("ow_damage: no pair ran")
        return EXIT_USAGE
    emit(f"{METRIC} = {value:.4f} over {len(results)} pair(s)")
    return EXIT_OK if passed == len(results) else EXIT_FAIL


if __name__ == "__main__":
    raise SystemExit(main())
